#! /bin/sh
#
# INIT script for Jitsi Gateway for SIP
# Version: 1.0  01-Aug-2014  yasen@bluejimp.com
#
### BEGIN INIT INFO
# Provides:          jigasi
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jitsi Gateway for SIP
# Description:       Gateway for Jitsi Meet to SIP
### END INIT INFO

. /etc/init.d/functions

# Include jigasi & videobridge defaults if available
if [ -f /etc/jitsi/jigasi/config ]; then
    . /etc/jitsi/jigasi/config
fi
if [ -f /etc/jitsi/videobridge/config ]; then
    . /etc/jitsi/videobridge/config
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/share/jigasi/jigasi.sh
DAEMON_DIR=/usr/share/jigasi/
NAME=jigasi
USER=jigasi
PIDPATH=/var/run/jitsi
PIDFILE="$PIDPATH"/jigasi.pid
LOGDIR=/var/log/jitsi
LOGFILE=$LOGDIR/jigasi.log
DESC=jigasi
if [ ! $JVB_HOST ]; then
    JVB_HOST=localhost
fi

JIGASI_SECRET=sipcall
DAEMON_OPTS=" --domain=$JIGASI_HOSTNAME --host=$JIGASI_HOST --port=5347 --secret=$JIGASI_SECRET --subdomain=$JIGASI_SUBDOMAIN --logdir=$LOGDIR --configdir=/etc/jitsi --configdirname=jigasi"

test -x $DAEMON || exit 0

set -e
if [ ! -d "$PIDPATH" ]; then
    mkdir "$PIDPATH";
    chown jigasi:jitsi "$PIDPATH";
    chmod 775 "$PIDPATH"
fi

if [ -d "$LOGDIR" ]; then
    rm -rf "$LOGFILE".*.lck
    rm -rf "$LOGFILE".[0-9].*
fi
killParentPid() {
    PARENT_PID=$(ps -o pid --no-headers --ppid $1 || true)
    if [ $PARENT_PID ]; then
        kill $PARENT_PID
    fi
}

stop() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
    fi
    echo -n "Stopping $DESC: "
    if [ $PID ]; then
        killParentPid $PID
#        kill -9 $PID
        rm $PIDFILE || true
        echo "$NAME stopped."
    elif [ $(ps -C jigasi.sh --no-headers -o pid) ]; then
        kill $(ps -o pid --no-headers --ppid $(ps -C jigasi.sh --no-headers -o pid)) || true
        rm $PIDFILE || true
        echo "$NAME stopped."
    else
        echo "$NAME doesn't seem to be running."
    fi
}
start() {
    if [ -f $PIDFILE ]; then
        echo "$DESC seems to be already running, we found pidfile $PIDFILE."
        exit 1
    fi
    echo -n "Starting $DESC: "

    #daemon --pidfile "$PIDFILE" --user $USER $CMD
    $DAEMON $DAEMON_OPTS < /dev/null &
    #$DAEMON $DAEMON_OPTS >> $LOGFILE 2>&1 &
#    start-stop-daemon --start --quiet --background --chuid $USER --make-pidfile --pidfile $PIDFILE \
#        --exec /bin/bash -- -c "exec $DAEMON $DAEMON_OPTS > $LOGFILE 2>&1"
    echo $! > $PIDFILE

    echo "$NAME started."
}

reload() {
    echo 'Not yet implemented.'
}

status() {
    printf "%-50s" "Checking $NAME..."
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  status)
    status
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|status}" >&2
    exit 1
    ;;
esac

exit 0

